#!/bin/bash

#The first line of the script is called SHEBANG
#SHEBANG line tells us the following script should be execute using bash interpreter

# TASK  2:  echo
#echo command is used to print the text on display in linux
echo "Welcome you all to the BashBlaze-7-Days-of-Bash-Scripting-Challenge"
                                                              
# TASK  3:  Variables
# We declare a variable in bash as shown below
# Variable_name=Value
# There are 2 types of variables 
a.System Variables - 
b.User defined variables - 

USER_NAME=Niranjan Janginmath
COURSE=Bash Scripting
DATE_OF_TODAY=`date`
VAR1=200
VAR2=100
ADD=$ ((VAR1+VAR2))
SUB=$ ((VAR1-VAR2))



# TASK  4:  Using variables
echo
echo "My system username is $USER_NAME, we will learn $COURSE concepts variable and wildcards on $DATE_OF_TODAY session"
echo
echo -e "Addition(VAR1+VAR2)=$ADD\nSubtraction(VAR1-VAR2)=$SUB"
echo



# TASK  5:   Using Built-in Variables
echo "My current bash path - $BASH"
echo "Bash version I am using - $BASH_VERSION"
echo "PID of bash I am running - $$"
echo "My home directory - $HOME"
echo "Where am I currently? - $PWD"
echo "My hostname - $HOSTNAME"



# Task  6: Wildcards
echo "Files with .txt extension in the current directory:"
ls *.txt







